name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Dependencies
        run: npm install --legacy-peer-deps

      - name: Generate .env Configuration
        run: |
          echo "EXPO_PUBLIC_API_URL=https://lumen-be.onrender.com/api/v1" >> .env
          echo "EXPO_PUBLIC_GOOGLE_WEB_CLIENT_ID=403396597474-jnou0b8qhvmqub6ev8p9t5baqopd33cj.apps.googleusercontent.com" >> .env

      - name: Expo Prebuild Android
        run: npx expo prebuild --platform android --clean

      - name: Build Standalone Release APK
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleRelease --no-daemon

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: lumen-android-release-apk
          path: android/app/build/outputs/apk/release/app-release.apk
